### ISSUE TITLE
0.36.0 - compiler error: macro []?(key) invalid macro name

### ISSUE THREAD

**Issue by dukenguyenxyz** [spider-gazelle/secrets-env#3]
Currently 0.36.0 is throwing this error for secrets-env as a shard

```crystal
In lib/secrets-env/src/secrets-env.cr:21:12

 21 | macro []?(key)
               ^
Error: invalid macro name
```

**Comment by stakach** [comment]
did crystal specifically disallow this? or could it be a `0.36.0` bug

**Comment by dukenguyenxyz** [comment]
Only failed since 0.36.0

**Comment by stakach** [comment]
yeah, however it might not be intentional that it fail for 0.36.0

**Comment by kimburgess** [comment]
Introduced by https://github.com/crystal-lang/crystal/pull/10069.

Taking a deeper look at this now. Will either resolve here, or submit a PR upstream depending on background for this change.

**Comment by kimburgess** [comment]
Went for option 3: both.

If the above PR is accepted the [conditional behaviour](https://github.com/spider-gazelle/secrets-env/blob/c3c51f72b5ba735caeb95446c72f1f041690da30/src/secrets-env.cr#L29) (and associated [spec skip](https://github.com/spider-gazelle/secrets-env/blob/c3c51f72b5ba735caeb95446c72f1f041690da30/spec/secrets-env_spec.cr#L107)) can be pinned down to only cover impacted compiler versions.
